"use client";

import { useState, useRef, useEffect } from "react";
import type { ItineraryData, TripFormData } from "@/lib/types";

interface ExportButtonProps {
  itinerary: ItineraryData;
  tripData: TripFormData;
}

function formatDayDate(dayIndex: number, arrivalDate?: string): string {
  if (!arrivalDate) return "";
  try {
    const date = new Date(arrivalDate + "T00:00:00");
    date.setDate(date.getDate() + dayIndex);
    return date.toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
    });
  } catch {
    return "";
  }
}

function generateMarkdown(
  itinerary: ItineraryData,
  tripData: TripFormData
): string {
  const lines: string[] = [];

  lines.push(`# Strictly ${tripData.city}`);
  lines.push(
    `*${tripData.duration} nights · ${tripData.companions} · ${tripData.vibes.join(", ")}*`
  );
  lines.push("");
  lines.push(itinerary.intro);
  lines.push("");

  if (tripData.hotel) {
    lines.push(`**Home Base:** ${tripData.hotel.name}`);
    if (tripData.hotel.address) lines.push(`*${tripData.hotel.address}*`);
    lines.push("");
  }

  for (const day of itinerary.days) {
    const dateStr = formatDayDate(day.day - 1, tripData.arrival?.date);
    lines.push(`## Day ${day.day}${dateStr ? ` — ${dateStr}` : ""}: ${day.title}`);
    lines.push("");

    for (const item of day.items) {
      const timeRange = item.endTime
        ? `${item.time} – ${item.endTime}`
        : item.time;
      lines.push(`### ${timeRange} · ${item.name}`);
      if (item.address) lines.push(`*${item.address}*`);
      lines.push(item.note);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(itinerary.signoff);
  lines.push("");
  lines.push("*Generated by Strictly The Good Stuff*");

  return lines.join("\n");
}

function generatePrintHTML(
  itinerary: ItineraryData,
  tripData: TripFormData
): string {
  const days = itinerary.days
    .map((day) => {
      const dateStr = formatDayDate(day.day - 1, tripData.arrival?.date);
      const items = day.items
        .map(
          (item) => `
        <div style="margin-bottom: 16px; padding: 12px 0; border-bottom: 1px solid #EDE7E1;">
          <div style="display: flex; gap: 16px;">
            <div style="width: 80px; text-align: right; flex-shrink: 0;">
              <span style="font-size: 12px; color: #B8937A; font-weight: 600;">${item.time}</span>
              ${item.endTime ? `<br><span style="font-size: 10px; color: #7A6E66;">— ${item.endTime}</span>` : ""}
            </div>
            <div style="flex: 1;">
              <span style="display: inline-block; padding: 2px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; border-radius: 999px; border: 1px solid #EDE7E1; color: #7A6E66; margin-bottom: 4px;">${item.type}</span>
              <h4 style="font-size: 16px; color: #2C2420; margin: 4px 0;">${item.name}</h4>
              ${item.address ? `<p style="font-size: 11px; color: #7A6E66; margin: 2px 0;">${item.address}</p>` : ""}
              <p style="font-size: 13px; color: #7A6E66; line-height: 1.6;">${item.note}</p>
            </div>
          </div>
        </div>`
        )
        .join("");

      return `
      <div style="margin-bottom: 32px; page-break-inside: avoid;">
        <div style="padding: 12px 0; margin-bottom: 8px; border-bottom: 2px solid #B8937A;">
          <span style="font-size: 11px; text-transform: uppercase; letter-spacing: 3px; color: #B8937A;">Day ${day.day}${dateStr ? ` — ${dateStr}` : ""}</span>
          <h3 style="font-size: 20px; color: #2C2420; margin: 4px 0 0 0;">${day.title}</h3>
        </div>
        ${items}
      </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Strictly ${tripData.city}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Roboto Mono', monospace; background: #FAF7F4; color: #2C2420; padding: 40px; max-width: 700px; margin: 0 auto; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div style="text-align: center; margin-bottom: 40px;">
    <p style="font-size: 11px; text-transform: uppercase; letter-spacing: 4px; color: #B8937A; margin-bottom: 8px;">Your Strict Itinerary</p>
    <h1 style="font-size: 32px; color: #2C2420;">Strictly ${tripData.city}</h1>
    <p style="font-size: 13px; color: #7A6E66; margin-top: 8px;">${tripData.duration} nights · ${tripData.companions} · ${tripData.vibes.join(", ")}</p>
  </div>
  <p style="text-align: center; font-size: 14px; color: #7A6E66; line-height: 1.6; max-width: 500px; margin: 0 auto 32px auto;">${itinerary.intro}</p>
  ${tripData.hotel ? `<div style="text-align: center; padding: 12px; background: #f0ece8; border-radius: 12px; margin-bottom: 32px;"><span style="font-size: 10px; text-transform: uppercase; letter-spacing: 2px; color: #5A70C4;">Home Base</span><br><strong>${tripData.hotel.name}</strong>${tripData.hotel.address ? `<br><span style="font-size: 11px; color: #7A6E66;">${tripData.hotel.address}</span>` : ""}</div>` : ""}
  ${days}
  <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #EDE7E1;">
    <p style="font-size: 16px; color: #B8937A; line-height: 1.6;">${itinerary.signoff}</p>
    <p style="font-size: 11px; color: #7A6E66; margin-top: 16px;">Generated by Strictly The Good Stuff</p>
  </div>
</body>
</html>`;
}

export default function ExportButton({
  itinerary,
  tripData,
}: ExportButtonProps) {
  const [showDropdown, setShowDropdown] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Close on click outside
  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(e.target as Node)
      ) {
        setShowDropdown(false);
      }
    };
    if (showDropdown) {
      document.addEventListener("mousedown", handleClick);
    }
    return () => document.removeEventListener("mousedown", handleClick);
  }, [showDropdown]);

  const exportMarkdown = () => {
    const md = generateMarkdown(itinerary, tripData);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `strictly-${tripData.city.toLowerCase().replace(/\s+/g, "-")}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setShowDropdown(false);
  };

  const exportPDF = () => {
    const html = generatePrintHTML(itinerary, tripData);
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(html);
    printWindow.document.close();
    // Give fonts a moment to load
    setTimeout(() => {
      printWindow.print();
    }, 500);
    setShowDropdown(false);
  };

  const copyToClipboard = async () => {
    const md = generateMarkdown(itinerary, tripData);
    try {
      await navigator.clipboard.writeText(md);
      setShowDropdown(false);
    } catch {
      // Fallback
      const textarea = document.createElement("textarea");
      textarea.value = md;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setShowDropdown(false);
    }
  };

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        onClick={() => setShowDropdown(!showDropdown)}
        className="px-5 py-2 rounded-full border border-border text-sm font-mono text-secondary hover:border-gold hover:text-brown transition-all"
      >
        Export
      </button>

      {showDropdown && (
        <div className="absolute right-0 top-full mt-2 w-48 bg-surface border border-border rounded-xl shadow-lg overflow-hidden z-20">
          <button
            onClick={exportPDF}
            className="w-full text-left px-4 py-3 text-sm font-mono text-brown hover:bg-light transition-colors"
          >
            Print / Save as PDF
          </button>
          <button
            onClick={exportMarkdown}
            className="w-full text-left px-4 py-3 text-sm font-mono text-brown hover:bg-light transition-colors border-t border-border"
          >
            Download Markdown
          </button>
          <button
            onClick={copyToClipboard}
            className="w-full text-left px-4 py-3 text-sm font-mono text-brown hover:bg-light transition-colors border-t border-border"
          >
            Copy to clipboard
          </button>
        </div>
      )}
    </div>
  );
}
